#ifndef CACHE_BRUTE_FORCE
#define CACHE_BRUTE_FORCE

#define BEAMFORMER_THREADS 128
#define BEAMS_PER_TB 4
#define BEAMS 4
#define ANTS 32

#define NUMREG 8
#define DIVINT 4
#define DIVINDM 32

#define DEDISP_DMS 32
#define DEDISP_THREADS 128

#define BANDPASS_THREADS 64

#define MEDIAN_WIDTH    5
#define MEDIAN_THREADS  256

#define MEAN_NUM_BLOCKS  512
#define MEAN_NUM_THREADS 256 

#define LOG_LOOKUP_LENGTH       32768
#define ENCODING_WRITE_OVERLAP  1

#define SHOW_BANDPASS 0
#endif
