add_subdirectory(mdsm-multibeam)
add_subdirectory(medicina-correlator-pipeline)
add_subdirectory(medicina-transient-pipeline)
#add_subdirectory(mdsm)
#add_subdirectory(mdsm-coherent)
#add_subdirectory(pelican-mdsm)
#add_subdirectory(standalone)
